name: Build and Run on all platforms

on:
  push:
  pull_request:

jobs:
  all:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 18
          - 20
          - 21
    name: ${{ matrix.os }} Node.js ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - uses: actions/checkout@v4

    - name: Prepare
      run: npm --color=always --silent install
    - name: Build
      run: npm --color=always --silent run build
    - name: Run
      run: npm --color=always --silent run start