name: Build and Run on all platforms

on:
  push:
  pull_request:

jobs:
  all:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
        exclude:
          # sys.exit(gyp.script_main())
          - os: macos-latest
            node_version: 14
    name: ${{ matrix.os }} Node.js ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - uses: actions/checkout@v2

    - name: Install winget
      if: matrix.os == 'windows-latest'
      uses: Cyberboss/install-winget@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Python
      if: matrix.os == 'windows-latest'
      run: winget install -e --id Python.Python.3.12
    - name: Install C++ Build Tools
      if: matrix.os == 'windows-latest'
      run: winget install -e --id Microsoft.VisualStudio.2022.Community --override "--quiet --add Microsoft.VisualStudio.Workload.VCTools"
  
    - name: Prepare
      run: npm --color=always --silent install
    - name: Build
      run: npm --color=always --silent run build
    - name: Run
      run: npm --color=always --silent run start